# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

##@ S3 tasks

.PHONY: create-s3-bucket
create-s3-bucket: ## Create a public S3 bucket (BUCKET_NAME=name REGION=region)
ifndef BUCKET_NAME
	$(error BUCKET_NAME is required)
endif
ifndef REGION
	$(error REGION is required)
endif
	@./scripts/create-public-s3-bucket.sh "$(BUCKET_NAME)" "$(REGION)"

.PHONY: verify-s3-bucket
verify-s3-bucket: ## Verify OIDC S3 bucket is defined and exists
	@./scripts/verify-s3-bucket.sh values-hypershift.yaml

.PHONY: install
install: verify-s3-bucket pattern-install ## Installs the pattern (verifies S3 bucket first)

include Makefile-common
