clusterGroup:
  name: staging
  isHubCluster: true
  sharedValueFiles:
    - /values-hypershift.yaml
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
    - '/overrides/values-{{ $.Values.global.clusterVersion }}-{{ $.Values.clusterGroup.name }}.yaml'

  namespaces:
    vault:
    external-secrets-operator:
      operatorGroup: true
      targetNamespaces: []
    external-secrets:
    multicluster-engine:
    cluster-provisioning:

  subscriptions:
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1
    
    mce:
      name: multicluster-engine
      namespace: multicluster-engine
      channel: stable-2.11
    
  argoProjects:
    - hub
    - hypershift
    - infrastructure

  applications:
    vault:
      name: vault
      namespace: vault
      argoProject: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*

    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      argoProject: hub
      chart: openshift-external-secrets
      chartVersion: 0.0.*

    hypershift:
      disabled: false
      name: hypershift
      namespace: multicluster-engine
      argoProject: hypershift
      chart: hypershift-config
      chartVersion: 0.0.*
  
    hypershift-cli:
      disabled: false
      name: hcp-cli
      namespace: cluster-provisioning
      argoProject: infrastructure
      path: charts/all/hcp-cli  

    autoscaler:
      disabled: false
      name: cluster-autoscaler
      namespace: openshift-machine-api
      argoProject: hypershift
      chart: cluster-autoscaler
      chartVersion: 0.0.*

  imperative:
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    namespace: imperative
    jobs:
    - name: hello-world
      # ansible playbook to be run
      playbook: rhvp.cluster_utils.hello_world
      # per playbook timeout in seconds
      timeout: 234
      # verbosity: "-v"

  managedClusterGroups:
    exampleRegion:
      name: group-one
      acmlabels:
      - name: clusterGroup
        value: group-one
      helmOverrides:
      - name: clusterGroup.isHubCluster
        value: false
